#!/usr/bin/env bash
# Setup iptables firewall rules to forward packets through the redsocks service

printf \
    'Info: Configuring the defensive interpreter behaviors...\n'
set_opts=(
    # Terminate script execution when an unhandled error occurs
    -o errexit
    -o errtrace

    # Terminate script execution when an unset parameter variable is
    # referenced
    -o nounset
)
if ! set "${set_opts[@]}"; then
    printf \
        'Error: Unable to configure the defensive interpreter behaviors.\n' \
        1>&2
    exit 1
fi

printf \
    'Info: Setting the ERR trap...\n'
if ! trap 'printf "Error: The program has encountered an unhandled error and is prematurely aborted.\\n" 1>&2' ERR; then
    printf \
        'Error: Unable to set the ERR trap.\n' \
        1>&2
    exit 1
fi

printf \
    'Info: Checking whether the running user is correct...\n'
if test "${EUID}" -ne 0; then
    printf \
        'Error: This program is required to be run as the superuser(root) user.\n' \
        1>&2
    exit 1
fi

printf \
    'Info: Creating the REDSOCKS nat table rule chain to host redsocks-specific packet filtering rules...\n'
if ! iptables -t nat -N REDSOCKS; then
    printf \
        'Error: Unable to create the REDSOCKS rule chain.\n' \
        1>&2
    exit 2
fi

printf \
    'Info: Avoid redirecting packets that are destined to the IPv4 private IP addresses...\n'
if ! iptables -t nat -A REDSOCKS -d 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16 -j RETURN; then
    printf \
        'Error: Unable to avoid redirecting packets that are destined to the IPv4 private IP addresses.\n' \
        1>&2
    exit 2
fi

printf \
    'Info: Avoid redirecting packets that are destined to the loopback IP addresses...\n'
if ! iptables -t nat -A REDSOCKS -d 127.0.0.0/8 -j RETURN; then
    printf \
        'Error: Unable to avoid redirecting packets that are destined to the loopback IP addresses.\n' \
        1>&2
    exit 2
fi

printf \
    'Info: Avoid redirecting packets that are destined to the Automatic Private IP Addressing(APIPA) IP addresses...\n'
if ! iptables -t nat -A REDSOCKS -d 169.254.0.0/16 -j RETURN; then
    printf \
        'Error: Unable to avoid redirecting packets that are destined to the Automatic Private IP Addressing(APIPA) IP addresses.\n' \
        1>&2
    exit 2
fi

printf \
    'Info: Avoid redirecting packets that are destined to the multicast IP addresses...\n'
if ! iptables -t nat -A REDSOCKS -d 224.0.0.0/4,240.0.0.0/4 -j RETURN; then
    printf \
        'Error: Unable to avoid redirecting packets that are destined to the Automatic Private IP Addressing(APIPA) IP addresses.\n' \
        1>&2
    exit 2
fi

printf \
    'Info: Redirecting all other packets to the redsocks service...\n'
if ! iptables -t nat -A REDSOCKS -p tcp -j REDIRECT --to-ports 12345; then
    printf \
        'Error: Unable to redirect all other packets to the redsocks service.\n' \
        1>&2
    exit 2
fi

printf \
    'Info: Redirecting all outgoing packets to the REDSOCKS rule chain...\n'
if ! iptables -t nat -A OUTPUT -j REDSOCKS; then
    printf \
        'Error: Unable to redirect all outgoing packets to the REDSOCKS rule chain.\n' \
        1>&2
    exit 2
fi

printf \
    'Info: Redirecting all incoming packets to the REDSOCKS rule chain...\n'
if ! iptables -t nat -A PREROUTING -p tcp --dport 443 -j REDSOCKS; then
    printf \
        'Error: Unable to redirect all incoming packets to the REDSOCKS rule chain.\n' \
        1>&2
    exit 2
fi
