#!/usr/bin/env bash
# Setup iptables firewall rules to forward packets through the redsocks service

printf \
    'Info: Configuring the defensive interpreter behaviors...\n'
set_opts=(
    # Terminate script execution when an unhandled error occurs
    -o errexit
    -o errtrace

    # Terminate script execution when an unset parameter variable is
    # referenced
    -o nounset
)
if ! set "${set_opts[@]}"; then
    printf \
        'Error: Unable to configure the defensive interpreter behaviors.\n' \
        1>&2
    exit 1
fi

printf \
    'Info: Setting the ERR trap...\n'
if ! trap 'printf "Error: The program has encountered an unhandled error and is prematurely aborted.\\n" 1>&2' ERR; then
    printf \
        'Error: Unable to set the ERR trap.\n' \
        1>&2
    exit 1
fi

# "set" is not the set builtin command
# shellcheck disable=SC2209
operation_mode=set

if test "${#}" -ne 0; then
    printf \
        'Info: Processing the command-line arguments...\n'
    while test "${#}" -ne 0; do
        case "${1}" in
            --help|-h)
                printf \
                    'Usage: %s [--help]\n' \
                    "${0}"
                exit 0
            ;;
            --reset|-r)
                operation_mode=reset
                shift
            ;;
            *)
                printf \
                    'Error: Unsupported command-line option "%s".\n' \
                    "${0}" \
                    1>&2
                exit 1
            ;;
        esac
    done
fi

printf \
    'Info: Checking whether the running user is correct...\n'
if test "${EUID}" -ne 0; then
    printf \
        'Error: This program is required to be run as the superuser(root) user.\n' \
        1>&2
    exit 1
fi

case "${operation_mode}" in
    set)
        if ! chain_rules="$(iptables -t nat -S REDSOCKS 2>/dev/null)"; then
            printf \
                'Info: Creating the REDSOCKS nat table rule chain to host redsocks-specific packet filtering rules...\n'
            if ! iptables -t nat -N REDSOCKS; then
                printf \
                    'Error: Unable to create the REDSOCKS rule chain.\n' \
                    1>&2
                exit 2
            fi
        fi

        if test "${chain_rules}" != '-N REDSOCKS'; then
            printf \
                'Info: Flushing the existing rules in the REDSOCKS rule chain...\n'
            if ! iptables -t nat -F REDSOCKS; then
                printf \
                    'Error: Unable to flush the existing rules in the REDSOCKS rule chain.\n' \
                    1>&2
                exit 2
            fi
        fi

        printf \
            'Info: Avoid redirecting packets that are destined to the IPv4 private IP addresses...\n'
        if ! iptables -t nat -A REDSOCKS -d 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16 -j RETURN; then
            printf \
                'Error: Unable to avoid redirecting packets that are destined to the IPv4 private IP addresses.\n' \
                1>&2
            exit 2
        fi

        printf \
            'Info: Avoid redirecting packets that are destined to the loopback IP addresses...\n'
        if ! iptables -t nat -A REDSOCKS -d 127.0.0.0/8 -j RETURN; then
            printf \
                'Error: Unable to avoid redirecting packets that are destined to the loopback IP addresses.\n' \
                1>&2
            exit 2
        fi

        printf \
            'Info: Avoid redirecting packets that are destined to the Automatic Private IP Addressing(APIPA) IP addresses...\n'
        if ! iptables -t nat -A REDSOCKS -d 169.254.0.0/16 -j RETURN; then
            printf \
                'Error: Unable to avoid redirecting packets that are destined to the Automatic Private IP Addressing(APIPA) IP addresses.\n' \
                1>&2
            exit 2
        fi

        printf \
            'Info: Avoid redirecting packets that are destined to the multicast IP addresses...\n'
        if ! iptables -t nat -A REDSOCKS -d 224.0.0.0/4,240.0.0.0/4 -j RETURN; then
            printf \
                'Error: Unable to avoid redirecting packets that are destined to the Automatic Private IP Addressing(APIPA) IP addresses.\n' \
                1>&2
            exit 2
        fi

        printf \
            'Info: Redirecting all other packets to the redsocks service...\n'
        if ! iptables -t nat -A REDSOCKS -p tcp -j REDIRECT --to-ports 12345; then
            printf \
                'Error: Unable to redirect all other packets to the redsocks service.\n' \
                1>&2
            exit 2
        fi

        if ! iptables -t nat -C OUTPUT -j REDSOCKS 2>/dev/null; then
            printf \
                'Info: Redirecting all outgoing packets to the REDSOCKS rule chain...\n'
            if ! iptables -t nat -A OUTPUT -j REDSOCKS; then
                printf \
                    'Error: Unable to redirect all outgoing packets to the REDSOCKS rule chain.\n' \
                    1>&2
                exit 2
            fi
        fi


        if ! iptables -t nat -C PREROUTING -j REDSOCKS 2>/dev/null; then
            printf \
                'Info: Redirecting all incoming packets to the REDSOCKS rule chain...\n'
            if ! iptables -t nat -A PREROUTING -j REDSOCKS; then
                printf \
                    'Error: Unable to redirect all incoming packets to the REDSOCKS rule chain.\n' \
                    1>&2
                exit 2
            fi
        fi
    ;;
    reset)
        if iptables -t nat -n -L REDSOCKS &>/dev/null; then
            if iptables -t nat -C PREROUTING -j REDSOCKS 2>/dev/null; then
                printf \
                    'Info: Removing the incoming packet redirection rule...\n'
                if ! iptables -t nat -D PREROUTING -j REDSOCKS; then
                    printf \
                        'Error: Unable to remove the incoming packet redirection rule.\n'
                    exit 2
                fi
            fi

            if iptables -t nat -C OUTPUT -j REDSOCKS 2>/dev/null; then
                printf \
                    'Info: Removing the outgoing packet redirection rule...\n'
                if ! iptables -t nat -D OUTPUT -j REDSOCKS; then
                    printf \
                        'Error: Unable to remove the outgoing packet redirection rule.\n'
                    exit 2
                fi
            fi

            if chain_rules="$(iptables -t nat -S REDSOCKS 2>/dev/null)"; then
                if test "${chain_rules}" != '-N REDSOCKS'; then
                    printf \
                        'Info: Flushing the REDSOCKS rule chain...\n'
                    if ! iptables -t nat -F REDSOCKS; then
                        printf \
                            'Error: Unable to flush the REDSOCKS rule chain.\n' \
                            1>&2
                        exit 2
                    fi
                fi

                printf \
                    'Info: Removing the REDSOCKS rule chain...\n'
                if ! iptables -t nat -X REDSOCKS; then
                    printf \
                        'Error: Unable to remove the REDSOCKS rule chain.\n' \
                        1>&2
                    exit 2
                fi
            fi
        fi
    ;;
    *)
        printf \
            'FATAL: The value of the operation_mode parameter is unsupported: %s.\n' \
            "${operation_mode}" \
            1>&2
        exit 99
    ;;
esac

printf \
    'Info: Operation completed without errors.\n'
